=== orgdm/gpfh/src/content/sustainability/sustainability.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://gpfh-assets.s3.amazonaws.com/about.schema.json",
  "title": "About",
  "description": "GPFH about page content",
  "type": "object",
  "properties": {
    "intro": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string"
        },
        "img": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "alt": {
              "type": "string"
            }
          }
        }
      }
    },
    "commitment": {
      "type": "object",
      "properties": {
        "title": {
          "type": "object",
          "properties": {
            "upper": {
              "type": "string"
            },
            "lower": {
              "type": "string"
            }
          }
        },
        "text": {
          "type": "string"
        },
        "img": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "alt": {
              "type": "string"
            }
          }
        }
      }
    },
    "nhba": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string"
        }
      }
    },
    "ecoFriendly": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string"
        },
        "img": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "alt": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "required": [
    "intro",
    "commitment",
    "ecoFriendly"
  ]
}

=== orgdm/gpfh/src/content/sustainability/sustainability.json
{
  "$schema": "./sustainability.schema.json",
  "intro": {
    "img": {
      "title": "Sustainability",
      "url": "/sunset.jpg",
      "alt": "Blue Ridge Mountains"
    },
    "text": "Our high quality materials will last for generations and your home will be more energy-efficient."
  },
  "commitment": {
    "title": {
      "upper": "GPFH Commitment",
      "lower": "to Sustainability"
    },
    "text": "In recent years, building homes with environmentally-friendly materials and practices has become increasingly important to our community and planet. Many luxury homebuilders have been slow to adopt “green” practices, but we believe it is our responsibility as a business to be good stewards of the land. We endeavor to minimize our environmental footprint in our business and with your custom home. For any client hoping to pursue a custom home using sustainable construction practices, we offer several options for you so that your home can be as “green” and environmentally-friendly as you desire.",
    "img": {
      "title": "Eco-Friendly Building",
      "url": "/gpfh_test_5.jpg",
      "alt": "building with sustainability in mind"
    }
  },
  "nhba": {
    "text": "Grove Park Fine Homes is an NHBA Certified Green Professional."
  },
  "ecoFriendly": {
    "text": "We embrace the natural beauty of the mountains of western North Carolina and we work to ensure that  all of our custom projects become a part of that landscape, not a distraction from it.",
    "img": {
      "title": "Eco-Friendly Building",
      "url": "/gpfh_test_7.jpg",
      "alt": "building with sustainability in mind"
    }
  }
}
